use std::collections::HashMap;
use serde::{Deserialize, Serialize};

/// A single attack specification generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttackSpec {
    /// HTTP method: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
    pub method: String,

    /// Full URL including injected payload in path/query.
    /// Validated against ScopeGuard before execution.
    pub url: String,

    /// Optional request headers.
    #[serde(default)]
    pub headers: HashMap<String, String>,

    /// Optional request body (for POST/PUT/PATCH).
    #[serde(default)]
    pub body: Option<String>,

    /// Content-Type for the body.
    #[serde(default = "default_content_type")]
    pub content_type: String,

    /// Human-readable description of what this attack tests.
    pub rationale: String,

    /// How to determine if the attack confirmed the vulnerability.
    pub success_indicator: SuccessIndicator,
}

fn default_content_type() -> String {
    "application/x-www-form-urlencoded".to_string()
}

/// How the executor determines if an attack confirmed the vulnerability.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SuccessIndicator {
    /// Response body contains this substring.
    BodyContains { pattern: String },
    /// Response HTTP status code matches exactly.
    StatusCode { code: u16 },
    /// Response header exists with this value substring.
    HeaderContains { header: String, pattern: String },
    /// Response body matches this regex pattern.
    BodyRegex { pattern: String },
}

/// The complete response from the LLM for a single finding analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmAnalysisResponse {
    /// LLM's assessment of the finding.
    pub analysis: String,

    /// Confidence that this is a true positive (0.0 – 1.0).
    pub confidence: f32,

    /// Generated attack specifications.
    #[serde(default)]
    pub attacks: Vec<AttackSpec>,

    /// Suggested remediation advice (may augment the existing finding remediation).
    #[serde(default)]
    pub remediation: Option<String>,
}

/// Result of executing a single AttackSpec.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct AttackResult {
    pub spec: AttackSpec,
    pub response_status: u16,
    pub response_body_snippet: String,
    pub confirmed: bool,
    pub elapsed_ms: u64,
}

/// Aggregated statistics for the LLM phase, included in the final report.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmStats {
    /// Number of findings sent to the LLM for analysis.
    pub findings_analyzed: usize,
    /// Total LLM API calls made.
    pub api_calls: usize,
    /// Total prompt tokens consumed.
    pub prompt_tokens: u64,
    /// Total completion tokens consumed.
    pub completion_tokens: u64,
    /// Number of attack specs generated across all findings.
    pub attacks_generated: usize,
    /// Number of attacks actually executed (0 in dry-run mode).
    pub attacks_executed: usize,
    /// Number of attacks that confirmed the vulnerability.
    pub attacks_confirmed: usize,
    /// Errors encountered (parse failures, API errors, etc.).
    pub errors: usize,
}

/// A message in a chat completion request.
#[derive(Debug, Clone, Serialize)]
pub struct PromptMessage {
    pub role: String,
    pub content: String,
}
